# Generated by Django 4.1.5 on 2023-03-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('1', 'Teacher'), ('2', 'Student')], default='2', max_length=10)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
