# Generated by Django 4.1.5 on 2023-03-09 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_role'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classrooms')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_copy', to='users.users')),
            ],
            options={
                'db_table': 'persons',
            },
        ),
    ]
