# Generated by Django 4.1.5 on 2023-03-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_date',
            field=models.DateField(auto_now=True),
        ),
    ]
