# Generated by Django 4.1.5 on 2023-03-10 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_users_role'),
        ('classes', '0002_persons'),
        ('doubt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('ans', models.TextField()),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classrooms')),
                ('doubt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doubt.doubts')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'answers',
            },
        ),
    ]
