# Generated by Django 4.1.5 on 2023-03-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='classrooms',
            table='classrooms',
        ),
    ]
