# Generated by Django 4.1.5 on 2023-03-07 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_alter_classrooms_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classrooms',
            old_name='name',
            new_name='classroom_name',
        ),
    ]
