# Generated by Django 4.1.5 on 2023-03-10 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_persons'),
        ('users', '0004_alter_users_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doubts',
            fields=[
                ('doubt_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classrooms')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'doubts',
            },
        ),
    ]
