# Generated by Django 4.1.5 on 2023-03-14 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_persons'),
        ('users', '0004_alter_users_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_title', models.TextField()),
                ('assignment', models.FileField(upload_to='assignments/')),
                ('deadline', models.DateField(auto_now=True)),
                ('max_marks', models.IntegerField()),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classrooms')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'assignments',
            },
        ),
    ]
